version: '3'
services:
  db:
    image: postgres
    restart: on-failure[3]
    environment:
      POSTGRES_USER: avangelov
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e_commerce_graphql
    ports:
      - 54320:5432
